version: '3'
services:
  node:
    build: ./
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - node-modules:/var/www/node_modules
    ports:
      - 3000:3000
    environment:
        PORT: 3000
        HOST: 0.0.0.0

volumes:
  node-modules:
